### ISSUE TITLE
Filter form missing from `object_list.html` template?

### ISSUE THREAD

**Issue by joshuadavidthomas** [westerveltco/neapolitan#12]

**Comment by carltongibson** [comment]
Yes, this should be added.

**Comment by joshuadavidthomas** [comment]
@jefftriplett fixed this in westerveltco/neapolitan#6 mostly -- it makes the filter available in the template's context, just need to adjust the `object_list.html` template to actually render it. But that PR also contains some unrelated QoL improvements around setting `list_fields` and `detail_fields` on a `CRUDView`. The `filterset` related code should be extracted so the any PR can just be targeted towards fixing the missing filter form.

**Comment by jefftriplett** [comment]
> But that PR also contains some unrelated QoL improvements around setting `list_fields` and `detail_fields` on a `CRUDView`. The `filterset` related code should be extracted so the any PR can just be targeted towards fixing the missing filter form.

I think the non-QoL additions might be useful to you. 

I suspect the rest may or may not be too opinionated 😮

**Comment by carltongibson** [comment]
Should be resolved by #42.
