### ISSUE TITLE
Make lookup field configurable

### ISSUE THREAD

**Issue by joshuadavidthomas** [westerveltco/neapolitan#5]
https://github.com/carltongibson/neapolitan/issues/11

https://github.com/westerveltco/neapolitan/blob/1347545df12abbfde32edb553d2bfad58484d907/src/neapolitan/views.py#L461-L465

https://github.com/carltongibson/neapolitan/pull/28 (though I don't particularly like `mount_url` as a variable tbh)

**Comment by carltongibson** [comment]
Yes, still pondering this one too.

**Comment by carltongibson** [comment]
Right, pondered. See https://github.com/carltongibson/neapolitan/pull/44
